spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

security:
  jwt:
    secret: 84c5a964feb7e63233460f8c3a8312f3
    expiration-ms: 86400000

admin:
  seed:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
